- name: Launch Ec2-instances
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: us-east-1
    ami_id: ami-09c813fb71547fc4f
    instance_type: t2.micro
    security_group: sg-08544cbe0920c82a5
    subnet_id: subnet-02ad4676bfc059370
    instance_name:
    - frontend
    - backend
    - mysql
  tasks:
    - name: Create ec2-instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ami_id }}"
        region: "{{ region }}"
        wait: yes
        count: 1
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group}}"
        tags:
          Name: "{{ item }}"
          Environment: Dev
      loop: "{{ instance_name }}"
      register: ec2_result