- name: Launch Ec2-instances
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - ec2_vars.yaml
  tasks:
    - name: Create ec2-instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ami_id }}"
        region: "{{ region }}"
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group}}"
        wait: yes
        count: 1
        tags:
          Name: "{{ item }}"
          Environment: Dev
      loop: "{{ instance_name }}"
      register: ec2_result

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ ec2_result }}"

    - name: create r53 record
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item }}.{{ zone }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
        overwrite: true

      loop: "{{ ec2_result.results}}"
    
